#!/usr/bin/env python3
"""Synchronize Claude Code and Codex project adapter files."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None


GENERATED = "Generated by claudet agent-config-sync."


class Syncer:
    def __init__(self, target: Path, direction: str, check: bool, force: bool) -> None:
        self.target = target.resolve()
        self.direction = direction
        self.check = check
        self.force = force
        self.changed = False
        self.blocked = False

    def run(self) -> int:
        if self.direction in {"both", "claude-to-codex"}:
            self.claude_to_codex()
        if self.direction in {"both", "codex-to-claude"}:
            self.codex_to_claude()
        if self.check and (self.changed or self.blocked):
            return 1
        return 0 if not self.blocked else 2

    def claude_to_codex(self) -> None:
        claude_md = self.target / "CLAUDE.md"
        if claude_md.exists():
            self.write_text(self.target / "AGENTS.md", self.render_agents_md(claude_md.read_text()))

        self.write_text(self.target / ".codex" / "config.toml", self.render_codex_config())

        for src in sorted((self.target / ".claude" / "agents").glob("*.md")):
            dst = self.target / ".codex" / "agents" / f"{slug(src.stem).replace('-', '_')}.toml"
            self.write_text(dst, self.render_codex_agent(src))

        for src in sorted((self.target / ".claude" / "commands").glob("*.md")):
            skill_dir = self.target / ".agents" / "skills" / f"claude-command-{slug(src.stem)}"
            self.write_text(skill_dir / "SKILL.md", self.render_command_skill(src))

        self.copy_project_skills(self.target / ".claude" / "skills", self.target / ".agents" / "skills")

    def codex_to_claude(self) -> None:
        agents_md = self.target / "AGENTS.md"
        claude_md = self.target / "CLAUDE.md"
        if agents_md.exists() and not claude_md.exists():
            self.write_text(claude_md, self.render_claude_md(agents_md.read_text()))

        for src in sorted((self.target / ".codex" / "agents").glob("*.toml")):
            rendered = self.render_claude_agent(src)
            if rendered:
                dst = self.target / ".claude" / "agents" / f"{src.stem.replace('_', '-')}.md"
                self.write_text(dst, rendered)

        skills_dir = self.target / ".agents" / "skills"
        for skill in sorted(skills_dir.iterdir() if skills_dir.exists() else []):
            if not skill.is_dir() or skill.name.startswith("claude-command-"):
                continue
            self.copy_tree(skill, self.target / ".claude" / "skills" / skill.name)

        mcp = self.render_claude_mcp()
        if mcp:
            self.write_text(self.target / ".mcp.json", mcp)

    def render_agents_md(self, claude_text: str) -> str:
        return f"""# Project Instructions for Codex

{GENERATED}

This file adapts `CLAUDE.md` for Codex. Follow the project rules below even when they mention Claude Code.

## Codex Compatibility

- Use `AGENTS.md` as the Codex entrypoint and `CLAUDE.md` as the canonical shared instruction source.
- Treat `.claude/rules/*.md` as shared project rules unless a closer `AGENTS.md` or `AGENTS.override.md` says otherwise.
- Keep `.codex/agents/*.toml` synchronized with `.claude/agents/*.md` when subagent behavior changes.
- Reusable claudet skills can be installed for Codex by running `make install` in the claudet repo.

## Canonical Instructions

{claude_text.rstrip()}
"""

    def render_claude_md(self, agents_text: str) -> str:
        return f"""# Project Instructions for Claude

{GENERATED}

This file adapts `AGENTS.md` for Claude Code. Follow the project rules below even when they mention Codex.

## Canonical Instructions

{agents_text.rstrip()}
"""

    def render_codex_config(self) -> str:
        servers = self.read_claude_mcp_servers()
        parts = [
            "# Project-scoped Codex adapter for Claude/Codex dual-agent projects.",
            f"# {GENERATED}",
            "",
            'project_doc_fallback_filenames = ["CLAUDE.md"]',
            "project_doc_max_bytes = 65536",
            "",
            "[agents]",
            "max_threads = 6",
            "max_depth = 1",
        ]
        for name, cfg in servers.items():
            parts.extend(["", f"[mcp_servers.{toml_key(name)}]"])
            if "command" in cfg:
                parts.append(f"command = {toml_string(str(cfg['command']))}")
            if "args" in cfg and isinstance(cfg["args"], list):
                args = ", ".join(toml_string(str(arg)) for arg in cfg["args"])
                parts.append(f"args = [{args}]")
            if "url" in cfg:
                parts.append(f"url = {toml_string(str(cfg['url']))}")
            if "env" in cfg and isinstance(cfg["env"], dict):
                parts.append(f"[mcp_servers.{toml_key(name)}.env]")
                for key, value in sorted(cfg["env"].items()):
                    parts.append(f"{toml_key(key)} = {toml_string(str(value))}")
        return "\n".join(parts).rstrip() + "\n"

    def render_codex_agent(self, src: Path) -> str:
        text = src.read_text().rstrip()
        name = slug(src.stem).replace("-", "_")
        description = extract_persona(text) or f"Custom agent converted from {src.relative_to(self.target)}."
        return "\n".join(
            [
                f"name = {toml_string(name)}",
                f"description = {toml_string(description)}",
                'sandbox_mode = "read-only"',
                f"developer_instructions = {toml_multiline(text)}",
                "",
            ]
        )

    def render_claude_agent(self, src: Path) -> str | None:
        if tomllib is None:
            self.note("BLOCK", f"{src}: Python 3.11+ tomllib is required to read TOML")
            self.blocked = True
            return None
        data = tomllib.loads(src.read_text())
        name = str(data.get("name") or src.stem.replace("_", " ").title())
        description = str(data.get("description") or "Converted Codex custom agent")
        instructions = str(data.get("developer_instructions") or "").rstrip()
        return f"""# Agent: {name.replace('_', ' ').title()}

**Type**: Isolated subagent
**Persona**: {description}

## Identity
{instructions}
"""

    def render_command_skill(self, src: Path) -> str:
        body = src.read_text().rstrip()
        command = slug(src.stem)
        return f"""---
name: claude-command-{command}
description: Use when the user wants the Claude `/{command}` command workflow in Codex, or asks to run `{command}` using the claudet command template.
---

# Claude Command: /{command}

{GENERATED}

Follow this workflow in Codex. The original Claude slash command body is below.

{body}
"""

    def render_claude_mcp(self) -> str | None:
        cfg = self.target / ".codex" / "config.toml"
        if not cfg.exists():
            return None
        if tomllib is None:
            self.note("BLOCK", f"{cfg}: Python 3.11+ tomllib is required to read TOML")
            self.blocked = True
            return None
        data = tomllib.loads(cfg.read_text())
        servers = data.get("mcp_servers")
        if not isinstance(servers, dict) or not servers:
            return None
        return json.dumps({"mcpServers": servers}, indent=2, sort_keys=True) + "\n"

    def read_claude_mcp_servers(self) -> dict[str, dict]:
        path = self.target / ".mcp.json"
        if not path.exists():
            return {}
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            self.note("BLOCK", f"{path}: invalid JSON: {exc}")
            self.blocked = True
            return {}
        servers = data.get("mcpServers", {})
        if not isinstance(servers, dict):
            return {}
        return {name: cfg for name, cfg in servers.items() if not name.startswith("_") and isinstance(cfg, dict)}

    def copy_project_skills(self, src_dir: Path, dst_dir: Path) -> None:
        if not src_dir.exists():
            return
        for skill in sorted(src_dir.iterdir()):
            if skill.is_dir() and (skill / "SKILL.md").exists():
                self.copy_tree(skill, dst_dir / skill.name)

    def copy_tree(self, src: Path, dst: Path) -> None:
        if not dst.exists():
            if self.check:
                self.note("NEW", str(dst.relative_to(self.target)))
                self.changed = True
                return
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(src, dst)
            self.note("COPY", str(dst.relative_to(self.target)))
            self.changed = True
            return
        if dirs_equal(src, dst):
            self.note("OK", str(dst.relative_to(self.target)))
            return
        if not self.force:
            self.note("SKIP", f"{dst.relative_to(self.target)} differs; use --force to overwrite")
            self.blocked = True
            return
        if self.check:
            self.note("STALE", str(dst.relative_to(self.target)))
            self.changed = True
            return
        shutil.rmtree(dst)
        shutil.copytree(src, dst)
        self.note("UPDATE", str(dst.relative_to(self.target)))
        self.changed = True

    def write_text(self, path: Path, content: str) -> None:
        rel = path.relative_to(self.target)
        if path.exists() and path.read_text() == content:
            self.note("OK", str(rel))
            return
        if path.exists() and not self.force and GENERATED not in path.read_text(errors="ignore"):
            self.note("SKIP", f"{rel} exists and is not generated; use --force to overwrite")
            self.blocked = True
            return
        if self.check:
            self.note("STALE" if path.exists() else "NEW", str(rel))
            self.changed = True
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        self.note("WRITE", str(rel))
        self.changed = True

    @staticmethod
    def note(kind: str, message: str) -> None:
        print(f"{kind:<6} {message}")


def slug(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "-", value.strip().lower()).strip("-")
    return value or "agent"


def extract_persona(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("**Persona**:"):
            return line.split(":", 1)[1].strip()
    return None


def toml_string(value: str) -> str:
    return json.dumps(value)


def toml_key(value: str) -> str:
    return value if re.match(r"^[A-Za-z0-9_-]+$", value) else toml_string(value)


def toml_multiline(value: str) -> str:
    safe = value.replace('"""', '\"\"\"')
    return f'"""\n{safe}\n"""'


def dirs_equal(left: Path, right: Path) -> bool:
    left_files = sorted(p.relative_to(left) for p in left.rglob("*") if p.is_file())
    right_files = sorted(p.relative_to(right) for p in right.rglob("*") if p.is_file())
    if left_files != right_files:
        return False
    return all((left / rel).read_bytes() == (right / rel).read_bytes() for rel in left_files)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=".", help="Project root to sync; defaults to current directory")
    parser.add_argument(
        "--direction",
        choices=["both", "claude-to-codex", "codex-to-claude"],
        default="both",
        help="Which adapter direction to generate",
    )
    parser.add_argument("--check", action="store_true", help="Report drift without writing files")
    parser.add_argument("--force", action="store_true", help="Overwrite stale generated or conflicting files")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    return Syncer(Path(args.target), args.direction, args.check, args.force).run()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
